### ISSUE TITLE
Hi, Can i use this as sign in service with zimbra's account ?

### ISSUE THREAD

**Issue by codetrash** [zimbra-api/zimbra-api#1]
I meant to make a single-sign-on service with zimbra email, can use this class ?

**Comment by xrevenge** [comment]
Hello,

I have the same problem. I can not use zimbra-api projetc.

Any ideaa?

**Comment by Setitch** [comment]
I fixed it using
```
    $js = new \Zimbra\Enum\RequestFormat('js');
    $api = new \Zimbra\Admin\Http('https://mailrelayserver.com/service/soap/', $js);
```

As for some reason the code provided in ,,tutorial'' was not working for me either.
