### ISSUE TITLE
Need documentation for the method "modifyAppointment"

### ISSUE THREAD

**Issue by idev2020** [zimbra-api/zimbra-api#14]
Hi nguyennv,

Thank you for this api.

Can you give me an example to use the method "modifyAppointment" ?

Thank you.

**Comment by nguyennv** [comment]
Hi idev2020
You can use example in https://github.com/zimbra-api/zimbra-api/issues/11 by replacing createAppointment with modifyAppointment and then pass appointment id to modifyAppointment

```php
$api->createAppointment($msg, $appointmentId);
```

**Comment by idev2020** [comment]
Hi nguyennv,

Thanks a lot for your help :+1:
