### ISSUE TITLE
how to use the call CancelAppointment()

### ISSUE THREAD

**Issue by szn256** [zimbra-api/zimbra-api#16]
CancelAppointment

**Comment by vmaury** [comment]
Hello szn256,
you've to call the method cancelAppointment ()
But the id (4th arg) is NOT the apptId :-$, it's the invId something like '1142-1141'
when the appointment is created, the response is something like 
```
(
    [invId] => 1142-1141
    [calItemId] => 1142
    [rev] => 4995
    [ms] => 4995
    [apptId] => 1142
)
```
And you've to put the compNum on 5th arg
so here's my complete code 
```
// $i is the appointment number, 1142 for ex.
$apt = $api->getAppointment(true, true, true, null, $i);
// print_r($apt); 
// The big astuce, il faut mettre comme id 'idApt-idInvt'
return $api->cancelAppointment(
	null, null, null, $i.'-'. $apt->appt->inv->id , $apt->appt->inv->comp->compNum, null, null
);
```

And it's the same thing for modifyAppointment method, the id to be indicated is like '1142-1141'
